/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./src/components/Little/Common/CommonHeader.vue')['default']
    DrawerDrawingBoard: typeof import('./src/components/ModelDrawer/DrawerDrawingBoard.vue')['default']
    DrawerHeader: typeof import('./src/components/ModelDrawer/DrawerHeader.vue')['default']
    DrawerSideBar: typeof import('./src/components/ModelDrawer/DrawerSideBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ImgCropper: typeof import('./src/components/Little/Util/ImgCropper.vue')['default']
    MaterialDetailMain: typeof import('./src/components/ModelMaterialDetail/MaterialDetailMain.vue')['default']
    MaterialFilter: typeof import('./src/components/ModelMaterial/MaterialFilter.vue')['default']
    MaterialHeader: typeof import('./src/components/ModelMaterial/MaterialHeader.vue')['default']
    MaterialItem: typeof import('./src/components/Little/Item/MaterialItem.vue')['default']
    MaterialMain: typeof import('./src/components/ModelMaterial/MaterialMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
