/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./src/components/Little/Common/CommonHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HomeDrawingBoard: typeof import('./src/components/ModelHome/HomeDrawingBoard.vue')['default']
    HomeHeader: typeof import('./src/components/ModelHome/HomeHeader.vue')['default']
    HomeSideBar: typeof import('./src/components/ModelHome/HomeSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
